<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Phone</name>
   <tag></tag>
   <elementGuidId>35e362e5-972c-411b-b5f8-6717106164fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,'ContactType')]//span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,'ContactType')]//span[1]</value>
      <webElementGuid>023bec74-f7f0-44de-b25f-787a12b3bcad</webElementGuid>
   </webElementProperties>
</WebElementEntity>
