<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TalkAbout2</name>
   <tag></tag>
   <elementGuidId>7af19b11-ff4a-42b7-9f90-b92364c155d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,'ConsultType')]//div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,'ConsultType')]//div[2]</value>
      <webElementGuid>f0f8cd24-91d4-4149-b1fd-d33f8cf9cf8a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
