<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TalkAbout4</name>
   <tag></tag>
   <elementGuidId>ed785ae0-3f92-43e7-8264-cf21dd4a45d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,'ConsultType')]//div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,'ConsultType')]//div[4]</value>
      <webElementGuid>65bb7a6d-784d-4953-b534-db74fc41d307</webElementGuid>
   </webElementProperties>
</WebElementEntity>
