<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SearchClinician</name>
   <tag></tag>
   <elementGuidId>32647c9f-dcd7-436f-8825-1fc9a2b44a7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@class='chosen-search-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@class='chosen-search-input']</value>
      <webElementGuid>fc6b4465-1356-4bab-8dfe-1c177fc7e902</webElementGuid>
   </webElementProperties>
</WebElementEntity>
