<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Clinician</name>
   <tag></tag>
   <elementGuidId>e959c120-f19e-4596-8988-ff992d46bb09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'ReviewDetails')]/div[2]/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'ReviewDetails')]/div[2]/div[2]/span</value>
      <webElementGuid>08a91a3f-7b0c-4acc-9e95-a776fd8ba3f1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
