<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DeclineNo</name>
   <tag></tag>
   <elementGuidId>34d732a3-d501-4086-a953-3e97b8e0f3ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'DeclineModal_block_wtActions')]//input[@value='No']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'DeclineModal_block_wtActions')]//input[@value='No']</value>
      <webElementGuid>8188b5b3-e91e-4d0e-859d-8af1952c638b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
