<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>e85733a3-47f5-44cb-a383-0b45f385d1ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'wtColumn1')]//input[@value='Cancel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'wtColumn1')]//input[@value='Cancel']</value>
      <webElementGuid>4e2a44a7-8b10-48bf-a34b-f6b20f1a6571</webElementGuid>
   </webElementProperties>
</WebElementEntity>
