<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SearchPatients</name>
   <tag></tag>
   <elementGuidId>11d222d6-b534-4b2e-986e-82fe57e2ee89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'nputSearchName')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'nputSearchName')]</value>
      <webElementGuid>435d67aa-10bd-49c5-8808-c055833d9736</webElementGuid>
   </webElementProperties>
</WebElementEntity>
