<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Patient</name>
   <tag></tag>
   <elementGuidId>7c3378d1-45fa-4e46-9a26-d6c8dea03284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[text()='Patient']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[text()='Patient']</value>
      <webElementGuid>a8832a29-bcce-4222-842a-fc20a36482de</webElementGuid>
   </webElementProperties>
</WebElementEntity>
