<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SaveThai</name>
   <tag></tag>
   <elementGuidId>0b5eb44e-8749-440e-9c68-0bb29e103b84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value='บันทึก']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value='บันทึก']</value>
      <webElementGuid>5e30ccaa-7f91-4f26-a889-f35a175fde38</webElementGuid>
   </webElementProperties>
</WebElementEntity>
