<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Language</name>
   <tag></tag>
   <elementGuidId>37d2dec7-601b-4180-8632-61e0e4b37560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'LocaleSelector')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'LocaleSelector')]</value>
      <webElementGuid>18ecc707-820c-45a2-ba18-c8c870d1551f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
