<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1_Name</name>
   <tag></tag>
   <elementGuidId>1b20b5bf-cafd-407e-ad29-5006e2375fe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'ConsultationsUpcoming')]//tbody//tr[1]//td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'ConsultationsUpcoming')]//tbody//tr[1]//td[1]</value>
      <webElementGuid>84810837-d448-4c2a-9885-b6b1bb43040c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
