<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_YesCancel</name>
   <tag></tag>
   <elementGuidId>e34c327d-e32e-4031-b67f-c977c6ee6af3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value='Yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value='Yes']</value>
      <webElementGuid>30d5f689-52c8-4c0b-bfa3-ce8e000ec4cd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
