<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal_cancel_message</name>
   <tag></tag>
   <elementGuidId>41b77a20-2992-4963-9689-fb9efb9a7a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,&quot;UnsavedChangesModal_block_wtContent&quot;)]//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,&quot;UnsavedChangesModal_block_wtContent&quot;)]//span</value>
      <webElementGuid>ba65149d-c7ef-40e8-a256-8c5022230501</webElementGuid>
   </webElementProperties>
</WebElementEntity>
