<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_FirstName</name>
   <tag></tag>
   <elementGuidId>34c0e0cb-f2e3-4fb1-b9e6-1fc67645c90a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,'Firstname')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,'Firstname')]</value>
      <webElementGuid>b608252b-39e9-4525-8d72-30ad3c0cc9b4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
