<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_Email</name>
   <tag></tag>
   <elementGuidId>6324fe4d-bd76-4280-8ad5-04f397eebadc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,'Email')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,'Email')]</value>
      <webElementGuid>56b6ec9d-1a53-424d-9145-29915cf35afe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
