<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StrenuousFrequency</name>
   <tag></tag>
   <elementGuidId>d3ef4e39-b2ec-4abd-b397-5da6165da442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'PHYICALSTRENUOUSFREQ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'PHYICALSTRENUOUSFREQ')]</value>
      <webElementGuid>ec586c77-5393-4060-944e-6b676afbd7ba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
