<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StrenuousDuration</name>
   <tag></tag>
   <elementGuidId>cc355cb7-8283-43b4-b2e7-57f707e92acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'PHYSICALSTRENUOUSDURMINS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'PHYSICALSTRENUOUSDURMINS')]</value>
      <webElementGuid>2ac6d8bc-ddc5-4df1-a795-6b45ce88d234</webElementGuid>
   </webElementProperties>
</WebElementEntity>
