<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ResistanceDuration</name>
   <tag></tag>
   <elementGuidId>567a7804-73a5-44bd-99e6-c3a454d8da46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'PHYSICALRESISTDDURMINS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'PHYSICALRESISTDDURMINS')]</value>
      <webElementGuid>6a446477-203f-4859-8b71-ae5792b71e2f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
