<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ModerateDuration</name>
   <tag></tag>
   <elementGuidId>697af560-8776-4b46-9e0a-7e34ec706fa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'PHYSICALMODDURMINS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'PHYSICALMODDURMINS')]</value>
      <webElementGuid>56083196-7843-4168-a67b-396fd3020e86</webElementGuid>
   </webElementProperties>
</WebElementEntity>
