<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ModerateFrequency</name>
   <tag></tag>
   <elementGuidId>b2e49933-91ce-467e-8f95-f6b9fde8982d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'PHYSICALMODFREQ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'PHYSICALMODFREQ')]</value>
      <webElementGuid>f45317c7-1d90-4752-b0fd-6394bbe0caac</webElementGuid>
   </webElementProperties>
</WebElementEntity>
