<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ResistanceFrequency</name>
   <tag></tag>
   <elementGuidId>d0461f5f-b228-41a5-a6f7-9cd43f269650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'PHYSICALRESISTFREQ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'PHYSICALRESISTFREQ')]</value>
      <webElementGuid>54f54c44-470e-4fd4-8d7a-01b6d2b02576</webElementGuid>
   </webElementProperties>
</WebElementEntity>
