<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MildFrequency</name>
   <tag></tag>
   <elementGuidId>9c1d0c80-f57b-406d-b146-659621bf2127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'PHYSICALMILDFREQ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'PHYSICALMILDFREQ')]</value>
      <webElementGuid>6ca06b73-0d6f-4405-9c29-b60128d6ec0b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
