<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MildDuration</name>
   <tag></tag>
   <elementGuidId>d8970893-9d61-40b2-b4e9-0c0949f8c8b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'PHYSICALMILDDURMINS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'PHYSICALMILDDURMINS')]</value>
      <webElementGuid>7139d084-6e84-491d-b9bb-fdc78d427c06</webElementGuid>
   </webElementProperties>
</WebElementEntity>
