<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_NeverRarely</name>
   <tag></tag>
   <elementGuidId>9390de90-afda-45f9-ad60-3dbb183548da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'PhysicalActivityDuration')]/div/span/div[3]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'PhysicalActivityDuration')]/div/span/div[3]//input</value>
      <webElementGuid>f757351b-a0e9-48cd-98a4-ff2663f4a9a8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
