<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Often</name>
   <tag></tag>
   <elementGuidId>cda95909-c3ba-4afa-b490-496737e6b9d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'PhysicalActivityDuration')]/div/span/div[1]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'PhysicalActivityDuration')]/div/span/div[1]//input</value>
      <webElementGuid>89c0d11c-bc61-41b8-830b-d669d78a3fb8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
