<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Sometimes</name>
   <tag></tag>
   <elementGuidId>3f23f0f3-be8f-48e9-a532-be5ec806eed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'PhysicalActivityDuration')]/div/span/div[2]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'PhysicalActivityDuration')]/div/span/div[2]//input</value>
      <webElementGuid>8a6c288e-3f8f-44e9-ac9b-f040305f1868</webElementGuid>
   </webElementProperties>
</WebElementEntity>
