<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OrgPostcode</name>
   <tag></tag>
   <elementGuidId>be176204-454d-46b2-9dca-542c1c20cfeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'ORGANISATIONPOSTCODE')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'ORGANISATIONPOSTCODE')]</value>
      <webElementGuid>2acafc33-58ce-4788-ae96-72e2418b30c6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
