<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_APHRAID</name>
   <tag></tag>
   <elementGuidId>0a8eb45b-98a7-41bc-b298-47a1fd290c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'AHPRA_HPI_I')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'AHPRA_HPI_I')]</value>
      <webElementGuid>6de80590-3536-4d1f-bdbc-ae71bab39d43</webElementGuid>
   </webElementProperties>
</WebElementEntity>
