<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_WeeklyWorkPattern</name>
   <tag></tag>
   <elementGuidId>1916ea3d-7527-43de-817f-a850f70d07e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id,&quot;Menu&quot;)][2]/div//span//div[3]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(@id,&quot;Menu&quot;)][2]/div//span//div[3]//a</value>
      <webElementGuid>ba966d30-b679-47e3-b955-d43f2ececa27</webElementGuid>
   </webElementProperties>
</WebElementEntity>
