<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_OrgState</name>
   <tag></tag>
   <elementGuidId>31d338f8-582e-4bc4-94a9-4089e792dc91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@id,'STATEID')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@id,'STATEID')]</value>
      <webElementGuid>21e33eeb-4ce4-40ca-8ea4-7576797cc6a3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
