<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Specialty</name>
   <tag></tag>
   <elementGuidId>050fe64b-7af0-4adb-9878-2a489beaf35a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@id,'SPECIALITYID')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@id,'SPECIALITYID')]</value>
      <webElementGuid>a55cdc65-3af5-43f5-9899-22bf7fc6934f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
