<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_BIO</name>
   <tag></tag>
   <elementGuidId>5b261729-3e0f-496c-9a1e-a126213d42a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[contains(@id,'BIO')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@id,'BIO')]</value>
      <webElementGuid>0d94c1b7-a6cb-4df8-8299-df9a4b982dbe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
