<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1_Name</name>
   <tag></tag>
   <elementGuidId>58fd6f92-bdc0-4877-944e-c81a1458de4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'ConsultationsPrevious')]//tbody//tr[1]//td[1]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'ConsultationsPrevious')]//tbody//tr[1]//td[1]//a</value>
      <webElementGuid>454ee6ef-1082-4e96-b515-1dca2dfed8ea</webElementGuid>
   </webElementProperties>
</WebElementEntity>
