<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Pending</name>
   <tag></tag>
   <elementGuidId>cf6b4f7e-3b3d-43f6-852e-fb8bfdb29f0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='Pending']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='Pending']</value>
      <webElementGuid>7f0051ef-5ac4-4572-a946-81d8927cbb26</webElementGuid>
   </webElementProperties>
</WebElementEntity>
