<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Today</name>
   <tag></tag>
   <elementGuidId>b410aea5-0258-492d-bc96-525b2afe33c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'Tabs_Header')]//div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'Tabs_Header')]//div[1]</value>
      <webElementGuid>af513423-57f4-4076-b045-fef4149f4f2f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
