<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Pending</name>
   <tag></tag>
   <elementGuidId>e0f25f3d-4b80-43f3-854d-98b37bc7a758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'Tabs_Header')]//div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'Tabs_Header')]//div[3]</value>
      <webElementGuid>6513a38c-3288-4594-9bd7-b339aea07c7f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
