<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Complete</name>
   <tag></tag>
   <elementGuidId>a2183eb6-e7f0-4093-8967-1ebbd0eec106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value='Complete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value='Complete']</value>
      <webElementGuid>369dce85-85a1-48f9-92fc-224f3db98fe1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
