<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1_Name</name>
   <tag></tag>
   <elementGuidId>e7bd2c98-ab49-496c-a9bf-781731aae2fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'ConsultationsToday')]//tbody//tr[1]//td[1]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'ConsultationsToday')]//tbody//tr[1]//td[1]//a</value>
      <webElementGuid>79a63aaa-374a-42f1-a798-670d27565993</webElementGuid>
   </webElementProperties>
</WebElementEntity>
