<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ResetSearchClinician</name>
   <tag></tag>
   <elementGuidId>9563b436-2633-4fc9-b3ad-671e0546787e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value='Reset']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value='Reset']</value>
      <webElementGuid>224c656b-adcb-49d2-9538-9f024167ce3e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
