<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_SearchResources</name>
   <tag></tag>
   <elementGuidId>1f3ca030-c24f-4889-9161-9b6c1a1de864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'lstbxTags')]/parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'lstbxTags')]/parent::div</value>
      <webElementGuid>84c41814-dbc8-4cb9-ac26-c6cef4705c79</webElementGuid>
   </webElementProperties>
</WebElementEntity>
