<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_result1</name>
   <tag></tag>
   <elementGuidId>7bc0e465-6aba-48e5-8397-ce82825306c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='select2-results']//li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='select2-results']//li[1]</value>
      <webElementGuid>fe593de7-0de7-4ef8-8088-a62d4486b7a8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
