<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_result2</name>
   <tag></tag>
   <elementGuidId>427c85b6-7497-497f-81bb-9f5886059508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='select2-results']//li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='select2-results']//li[2]</value>
      <webElementGuid>aea9ae10-6cdd-4d0a-8f91-e828278c1932</webElementGuid>
   </webElementProperties>
</WebElementEntity>
