<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Resources</name>
   <tag></tag>
   <elementGuidId>642c3593-3db0-4ef1-a6a8-87fc55f82b7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'SearchBar')]//select[contains(@id,'lstbxTags')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'SearchBar')]//select[contains(@id,'lstbxTags')]</value>
      <webElementGuid>3fe87e3b-cf23-4f35-9bc0-b18d484f461f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
