<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1</name>
   <tag></tag>
   <elementGuidId>a8aaa749-dda3-44a4-acfc-9076a95b2631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'ConsultationsPrevious')]//tbody//tr[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'ConsultationsPrevious')]//tbody//tr[1]</value>
      <webElementGuid>2e989924-3817-4588-bbfb-ea0eb7410232</webElementGuid>
   </webElementProperties>
</WebElementEntity>
