<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>3c5b15ef-5407-4020-b205-29dcaa11be27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'wtctn_Button')]//input[@value='Update']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'wtctn_Button')]//input[@value='Update']</value>
      <webElementGuid>5e619e5a-b0dc-43ca-a746-cd32ac74e612</webElementGuid>
   </webElementProperties>
</WebElementEntity>
