<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_input_Comment</name>
   <tag></tag>
   <elementGuidId>f0529500-ba11-4039-a292-9e6fae92ee3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[contains(@name,'LifeEvent_COMMENT')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@name,'LifeEvent_COMMENT')]</value>
      <webElementGuid>85166d68-1fe2-4fde-ac49-6f45ee239350</webElementGuid>
   </webElementProperties>
</WebElementEntity>
