<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StartDate</name>
   <tag></tag>
   <elementGuidId>0fe0f658-8143-4ecc-8f25-70291b75ae71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'LifeEventSubType')]//input[contains(@name,'EVENTSTARTDATE')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'LifeEventSubType')]//input[contains(@name,'EVENTSTARTDATE')]</value>
      <webElementGuid>98096de5-5964-42b3-a82e-cf8c97b9e592</webElementGuid>
   </webElementProperties>
</WebElementEntity>
