<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Date</name>
   <tag></tag>
   <elementGuidId>61cfd50f-d943-4620-a8e4-4543f368cf86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,'wtExpression_Date')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,'wtExpression_Date')]</value>
      <webElementGuid>a5b9eb70-2d26-4ce9-b8d7-5c77cca9438a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
