<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_TreatmentStatus</name>
   <tag></tag>
   <elementGuidId>8da100b0-3ccd-43ab-8413-387b4ad7f1ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'ErrorStatus')]//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'ErrorStatus')]//span</value>
      <webElementGuid>b1b5b50a-d2c7-4823-9d1b-76d808b02068</webElementGuid>
   </webElementProperties>
</WebElementEntity>
