<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_TreatmentType</name>
   <tag></tag>
   <elementGuidId>532c2772-f3a1-44d3-98ad-ceeb5e5f7169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'LifeEventSubType')]//span[contains(@id,'LIFEEVENTSUBTYPEID')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'LifeEventSubType')]//span[contains(@id,'LIFEEVENTSUBTYPEID')]</value>
      <webElementGuid>37a87664-c720-46b2-be92-bdfd2b42cfba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
