<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SearchClinician</name>
   <tag></tag>
   <elementGuidId>ac299ce9-28e7-4257-9e5d-39d3afa12584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value='Search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value='Search']</value>
      <webElementGuid>6f855be7-e814-4369-a28e-799c313771ff</webElementGuid>
   </webElementProperties>
</WebElementEntity>
