<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SearchReset</name>
   <tag></tag>
   <elementGuidId>0bb22322-1153-4aed-8b48-6f42b0cf5d99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value='Reset']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value='Reset']</value>
      <webElementGuid>65ed4687-b36c-4cb9-acd9-0dd3291cdb47</webElementGuid>
   </webElementProperties>
</WebElementEntity>
