<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SearchClinician</name>
   <tag></tag>
   <elementGuidId>45358449-afd4-4bf5-bf98-f31ae23e182f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'wtBreadcrumbs_wtctn__Search')]//input[contains(@id,'inputSearch')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'wtBreadcrumbs_wtctn__Search')]//input[contains(@id,'inputSearch')]</value>
      <webElementGuid>523f8442-bb59-4246-927e-575210ed45ef</webElementGuid>
   </webElementProperties>
</WebElementEntity>
