<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1_LastName</name>
   <tag></tag>
   <elementGuidId>fd42cc8e-b3eb-4ab2-9e67-666ed17ccbeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'ClinicianTable')]//tbody//tr[1]//td[1]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'ClinicianTable')]//tbody//tr[1]//td[1]//a</value>
      <webElementGuid>9daac945-f364-467e-b541-b89797fe26fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
