<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Note</name>
   <tag></tag>
   <elementGuidId>86b547ea-90a5-4a81-93aa-7afadfa40bf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[contains(@id,'Input_Note')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@id,'Input_Note')]</value>
      <webElementGuid>cfe98ffe-941d-467c-8d33-c9146bb4d9a8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
