<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_SearchResource</name>
   <tag></tag>
   <elementGuidId>0afdbcec-ab4e-4315-be41-574d1cc9fe34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@id,'lstbxTags')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@id,'lstbxTags')]</value>
      <webElementGuid>849fc038-b998-4def-ac1e-e3a19e539e59</webElementGuid>
   </webElementProperties>
</WebElementEntity>
