<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_SearchResources</name>
   <tag></tag>
   <elementGuidId>8135eec1-5832-4b14-8359-18c3f7e8cf18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'lstbxTags')]/parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'lstbxTags')]/parent::div</value>
      <webElementGuid>589cd521-a45f-401e-b8f6-dce332999ff9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
