<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SearchResources1</name>
   <tag></tag>
   <elementGuidId>c67371b1-a321-47db-8986-4f843431db71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='s2id_autogen29']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='s2id_autogen29']</value>
      <webElementGuid>8653306a-7497-466d-b0e5-cdac8c07c2ea</webElementGuid>
   </webElementProperties>
</WebElementEntity>
