<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SearchResource2</name>
   <tag></tag>
   <elementGuidId>cc8be906-378e-4b1b-afff-a2dd09edbe4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'lstbxTags')]/parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'lstbxTags')]/parent::div</value>
      <webElementGuid>931dbc70-4cb0-4179-b722-c6b635322ecb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
