<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SearchResources</name>
   <tag></tag>
   <elementGuidId>75bed8a0-8a77-425d-a63d-b63dc951db37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@class='select2-search-field']//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@class='select2-search-field']//input</value>
      <webElementGuid>2c19f729-f7d7-4fdc-9792-ac0a028508cb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
