<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_SearchDepression</name>
   <tag></tag>
   <elementGuidId>27617466-d436-4f84-a45b-0e10e54a9974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='Depression']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='Depression']</value>
      <webElementGuid>e72cd121-2e04-46fd-947c-56fa92cbb380</webElementGuid>
   </webElementProperties>
</WebElementEntity>
