<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page_Title</name>
   <tag></tag>
   <elementGuidId>390bd60f-3656-49ab-bf59-ba6328659016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='heading1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class='heading1']</value>
      <webElementGuid>9342955e-40b7-427d-a855-66ccfd068f41</webElementGuid>
   </webElementProperties>
</WebElementEntity>
