<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_result2</name>
   <tag></tag>
   <elementGuidId>f37c9f3c-64d2-4e61-981f-1b826e5513b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='select2-results']//li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='select2-results']//li[2]</value>
      <webElementGuid>a2c699a3-e1e1-4f7b-9df3-e5f18522def8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
