<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_result1</name>
   <tag></tag>
   <elementGuidId>9c732f11-d22d-486a-9cdf-173ec724ff90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='select2-results']//li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='select2-results']//li[1]</value>
      <webElementGuid>ed9eca23-f915-48f2-b5e2-bacdaaf381be</webElementGuid>
   </webElementProperties>
</WebElementEntity>
