<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Resources</name>
   <tag></tag>
   <elementGuidId>72a6e453-7a7a-40dc-8fe4-eedaa4e6832c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'SearchBar')]//select[contains(@id,'lstbxTags')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'SearchBar')]//select[contains(@id,'lstbxTags')]</value>
      <webElementGuid>6dec06f0-410d-4465-a18e-39ffd4f035f1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
