<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>1e42987c-4793-428b-8fe3-0cc10c500d28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'wtPSA_block_wtContent')]//input[@value='Cancel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'wtPSA_block_wtContent')]//input[@value='Cancel']</value>
      <webElementGuid>bafb4e39-70cd-423f-8b60-b456197693eb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
