<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date</name>
   <tag></tag>
   <elementGuidId>25be67df-3e4d-474c-aed3-d1d0f72f92f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'HealthIndicatorForm')]//following-sibling::input[contains(@name,'LifeEvent_LIFEEVENTDUEDATE')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'HealthIndicatorForm')]//following-sibling::input[contains(@name,'LifeEvent_LIFEEVENTDUEDATE')]</value>
      <webElementGuid>65dda230-8cfd-4cff-8902-39acc80d7802</webElementGuid>
   </webElementProperties>
</WebElementEntity>
