<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1_MenuCancel</name>
   <tag></tag>
   <elementGuidId>6c9995d6-573d-41e8-a70b-cfd385826334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'PendingConsultationTable')]//tbody//tr[1]//td[5]//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'PendingConsultationTable')]//tbody//tr[1]//td[5]//span</value>
      <webElementGuid>a549c94c-66a2-444f-aa23-2d4f30e0e5e1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
