<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1_Name</name>
   <tag></tag>
   <elementGuidId>f2b3c8c7-b9aa-417f-b0b1-f5b170f45cf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'PendingConsultationTable')]//tbody//tr[1]//td[1]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'PendingConsultationTable')]//tbody//tr[1]//td[1]//a</value>
      <webElementGuid>f2f13ed6-fd3a-44da-8441-4be37aad21e0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
