<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_FileModalClose</name>
   <tag></tag>
   <elementGuidId>25595302-be08-46d0-81d9-21e2b68cc979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value='Close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value='Close']</value>
      <webElementGuid>b7e32df8-e1c3-4bb8-8e33-53afd8275398</webElementGuid>
   </webElementProperties>
</WebElementEntity>
