<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_UploadImage</name>
   <tag></tag>
   <elementGuidId>6c7bb571-2aca-45c1-b7fd-6c9717d54c0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='ctr_UploadButton']//div[2]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='ctr_UploadButton']//div[2]//input</value>
      <webElementGuid>fde26d59-fe48-4d5f-8022-1a66d2e0a296</webElementGuid>
   </webElementProperties>
</WebElementEntity>
