<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PreferredName</name>
   <tag></tag>
   <elementGuidId>6afbafc8-fcc6-42e2-a6ff-087205528c6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'PREFERREDNAME')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'PREFERREDNAME')]</value>
      <webElementGuid>81991702-867d-454c-9ca3-fe970b104e7c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
