<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postcode</name>
   <tag></tag>
   <elementGuidId>4c018bd3-aa4a-4a57-81d3-5abe75345964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'POSTCODE')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'POSTCODE')]</value>
      <webElementGuid>fbe04736-f7ff-43da-9282-cdcc935f4f35</webElementGuid>
   </webElementProperties>
</WebElementEntity>
