<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_UserPreferences</name>
   <tag></tag>
   <elementGuidId>875932e3-8666-4f07-a8c8-49ac82618b9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id,&quot;profilemenu&quot;)][2]/div//span//div[3]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(@id,&quot;profilemenu&quot;)][2]/div//span//div[3]//a</value>
      <webElementGuid>41a6760a-5dff-431e-bcff-ec66578b9f57</webElementGuid>
   </webElementProperties>
</WebElementEntity>
