<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_BasicInfo</name>
   <tag></tag>
   <elementGuidId>913314b6-e604-404e-806d-df5b62d2fbdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id,&quot;profilemenu&quot;)][2]/div//span//div[1]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(@id,&quot;profilemenu&quot;)][2]/div//span//div[1]//a</value>
      <webElementGuid>c1f062a8-3945-422a-80aa-1ecfdbd32d58</webElementGuid>
   </webElementProperties>
</WebElementEntity>
