<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_GenderID</name>
   <tag></tag>
   <elementGuidId>a7f6cf2d-11f5-4f46-b374-5702d317cc9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@id,'GENDERID')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@id,'GENDERID')]</value>
      <webElementGuid>c08ad62f-55f3-44a9-801b-a0d5fc0cc76e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
