<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Appointments</name>
   <tag></tag>
   <elementGuidId>75b70886-cfea-461f-9381-75edcbdacc10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='Appointments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='Appointments']</value>
      <webElementGuid>9bbec694-25b8-4528-8f4f-d54edaaddf36</webElementGuid>
   </webElementProperties>
</WebElementEntity>
