<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Logout</name>
   <tag></tag>
   <elementGuidId>180813db-ac00-467f-927f-fd29f249b46c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='Logout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='Logout']</value>
      <webElementGuid>18cf8d79-d735-445c-acd1-e3836c404a36</webElementGuid>
   </webElementProperties>
</WebElementEntity>
