<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Clinicians</name>
   <tag></tag>
   <elementGuidId>fbd039ce-4060-407f-8504-5e488fd248f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='Clinicians']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='Clinicians']</value>
      <webElementGuid>8f75143b-f8ea-4061-823f-a6caf3be6f39</webElementGuid>
   </webElementProperties>
</WebElementEntity>
