<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_RestlessMorethan</name>
   <tag></tag>
   <elementGuidId>640edbf3-9840-4928-bc77-b3565debd693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus4']//div[contains(@id,'RangeSliderObject')]/div[2]/div[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus4']//div[contains(@id,'RangeSliderObject')]/div[2]/div[8]</value>
      <webElementGuid>9c7fcd65-69cd-405a-b686-45184eaabaff</webElementGuid>
   </webElementProperties>
</WebElementEntity>
