<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_FeelingNervousNotAtAll</name>
   <tag></tag>
   <elementGuidId>32d55c5f-7cf0-429d-9765-78aeab742393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus0']//div[contains(@id,'RangeSliderObject')]/div[2]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus0']//div[contains(@id,'RangeSliderObject')]/div[2]/div[4]</value>
      <webElementGuid>64a574ff-b366-4204-965e-980d0d092dd7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
