<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_AfraidSeveral</name>
   <tag></tag>
   <elementGuidId>62a5cd84-a8a8-4a71-ba24-7d167f14bc04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus6']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus6']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      <webElementGuid>797f845e-a623-4858-b507-96c00ed7b3a3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
