<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_TroubleRelaxNearly</name>
   <tag></tag>
   <elementGuidId>0d06a4e2-56e2-4960-8023-6fb1e90cb851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus3']//div[contains(@id,'RangeSliderObject')]/div[2]/div[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus3']//div[contains(@id,'RangeSliderObject')]/div[2]/div[10]</value>
      <webElementGuid>ff428cf1-54ee-490e-aa3f-57410ddb10ae</webElementGuid>
   </webElementProperties>
</WebElementEntity>
