<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_AbletoStopSeveral</name>
   <tag></tag>
   <elementGuidId>d09ace1b-caa5-423c-97e5-b9ffac5d1557</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus1']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus1']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      <webElementGuid>a93f95a3-1a1d-46c1-a653-c98d0eecd120</webElementGuid>
   </webElementProperties>
</WebElementEntity>
