<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_WorryingSeveral</name>
   <tag></tag>
   <elementGuidId>8a91d48e-366c-45db-b01f-9ec8c9953a57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus2']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus2']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      <webElementGuid>6ef1fa24-3e6c-4760-ba9b-7505f00b00fc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
