<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_AnnoyedSeveral</name>
   <tag></tag>
   <elementGuidId>a276828a-046d-4cf8-91b0-83d964a598ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus5']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus5']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      <webElementGuid>7c8ff576-d21e-4d86-98b7-283b52a54fd5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
