<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CancelYes</name>
   <tag></tag>
   <elementGuidId>2f37830b-1e41-477e-8861-c64a5f33373c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value='Yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value='Yes']</value>
      <webElementGuid>074877f7-1023-4ced-98a7-e6d25e4f5226</webElementGuid>
   </webElementProperties>
</WebElementEntity>
