<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_ClinicianSpecialty</name>
   <tag></tag>
   <elementGuidId>4cf739f5-cc12-4da5-b6f5-f3822ebefff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@id,'Clinician_ClinicianSpeciality')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@id,'Clinician_ClinicianSpeciality')]</value>
      <webElementGuid>f5797813-79f5-4ce2-85ab-573a3083b31d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
