<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ClinicianLastName</name>
   <tag></tag>
   <elementGuidId>6d88ec1a-814a-4203-9ad1-4d3be8d248bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'Clinician_LastName')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'Clinician_LastName')]</value>
      <webElementGuid>6fdbfa0d-2cdb-49c4-a41e-d3dc61107208</webElementGuid>
   </webElementProperties>
</WebElementEntity>
