<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_Specialty</name>
   <tag></tag>
   <elementGuidId>c4da77ca-5e88-43d6-babd-443b4a100033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,'Clinician_ClinicianSpeciality')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,'Clinician_ClinicianSpeciality')]</value>
      <webElementGuid>cea4a015-de04-4ce0-92a5-e727df7f3e86</webElementGuid>
   </webElementProperties>
</WebElementEntity>
