<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1</name>
   <tag></tag>
   <elementGuidId>925c5ef9-dc9c-457b-8d3f-9b966dd16bd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'TodayConsultationTable')]//tbody//tr[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'TodayConsultationTable')]//tbody//tr[1]</value>
      <webElementGuid>89ecab28-0aac-45c8-9954-daadc58d6b16</webElementGuid>
   </webElementProperties>
</WebElementEntity>
