<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1_Name</name>
   <tag></tag>
   <elementGuidId>6176364d-5e4c-47ed-93be-f1d2dcaea156</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'TodayConsultationTable')]//tbody//tr[1]//td[1]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'TodayConsultationTable')]//tbody//tr[1]//td[1]//a</value>
      <webElementGuid>fdf89e08-8c38-42da-93ae-a669ae70d08d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
