<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1</name>
   <tag></tag>
   <elementGuidId>5a2fe890-3c7e-44b9-b0de-c9e8cc02d1f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'UpcomingConsultationTablee')]//tbody//tr[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'UpcomingConsultationTablee')]//tbody//tr[1]</value>
      <webElementGuid>a7bfa468-3651-4d8f-94b4-fb035176e27d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
