<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1_Name</name>
   <tag></tag>
   <elementGuidId>d0088ffe-b0e3-49e0-9351-072b1c56a419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'UpcomingConsultationTable')]//tbody//tr[1]//td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'UpcomingConsultationTable')]//tbody//tr[1]//td[1]</value>
      <webElementGuid>bfd69f0d-6a65-4381-9aaf-664bc8eccb59</webElementGuid>
   </webElementProperties>
</WebElementEntity>
