<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Login</name>
   <tag></tag>
   <elementGuidId>511c2e8c-02cd-4cd7-832e-1006ec712ee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='heading1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class='heading1']</value>
      <webElementGuid>d52aebc7-2f0c-49b7-8232-2717adc02032</webElementGuid>
   </webElementProperties>
</WebElementEntity>
