<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DeclineNo</name>
   <tag></tag>
   <elementGuidId>f8c22894-f046-4625-965d-d8b714e2183b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'DeclineModal_block_wtActions')]//input[@value='No']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'DeclineModal_block_wtActions')]//input[@value='No']</value>
      <webElementGuid>502842da-230b-4384-b259-48ed39743ee1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
