<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DeclineYes</name>
   <tag></tag>
   <elementGuidId>2f69058e-92b6-43a5-90c6-aa88fa72da4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'DeclineModal_block_wtActions')]//input[@value='Yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'DeclineModal_block_wtActions')]//input[@value='Yes']</value>
      <webElementGuid>610b9a13-5f32-465c-bf94-2e6c12976a47</webElementGuid>
   </webElementProperties>
</WebElementEntity>
