<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ApproveOk</name>
   <tag></tag>
   <elementGuidId>1d6fda5f-cc99-42c8-baea-c50037bf013e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'Success_block_wtActions')]//input[@value='Ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'Success_block_wtActions')]//input[@value='Ok']</value>
      <webElementGuid>ff7fde50-4227-4454-9e12-c9fbd12e8ce4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
