<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal_Decline</name>
   <tag></tag>
   <elementGuidId>b296e56d-fe29-498c-976a-945f01ae275d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='DBHealthWidgets_wtDeclineModal_block']//div[@class='card']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='DBHealthWidgets_wtDeclineModal_block']//div[@class='card']</value>
      <webElementGuid>d8c08b51-28fb-40bd-9a03-17868b63c9b7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
