<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal_Approve</name>
   <tag></tag>
   <elementGuidId>fb003ab3-6826-4d0b-a34d-b300cf6eb503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='DBHealthWidgets_wtSuccess_block']//div[@class='card']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='DBHealthWidgets_wtSuccess_block']//div[@class='card']</value>
      <webElementGuid>f0f847ad-9f47-4283-8859-d0aa196bc400</webElementGuid>
   </webElementProperties>
</WebElementEntity>
