<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1_Decline</name>
   <tag></tag>
   <elementGuidId>c88a7e2b-42c0-46f4-8db0-050df8991e20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'ConsultationsRequested')]//tbody//tr[1]//td[8]//input[@value='Decline']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'ConsultationsRequested')]//tbody//tr[1]//td[8]//input[@value='Decline']</value>
      <webElementGuid>6cc34373-61fb-4230-a6bf-a133ac7fe3f7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
