<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1_Approve</name>
   <tag></tag>
   <elementGuidId>ae1b6bac-1569-4eb3-805a-9314f296fd59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'ConsultationsRequested')]//tbody//tr[1]//td[8]//input[@value='Approve']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'ConsultationsRequested')]//tbody//tr[1]//td[8]//input[@value='Approve']</value>
      <webElementGuid>a5204002-5347-4d79-a90d-cfd4e27b07d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
