<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Note</name>
   <tag></tag>
   <elementGuidId>8098132d-6db4-41c8-8aaa-3ec87c7a536c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[contains(@id,'Input_Note')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@id,'Input_Note')]</value>
      <webElementGuid>10a880d5-dd99-4ff2-86ea-62de557541ba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
