<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DeclinePatient</name>
   <tag></tag>
   <elementGuidId>f721d091-0d84-4a1a-a9db-b0beec95b6a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@value='Decline'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@value='Decline'])[1]</value>
      <webElementGuid>9196fb1a-e2c3-4c59-a226-3906989b46ee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
