<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ApprovePatient</name>
   <tag></tag>
   <elementGuidId>5dcf227b-5ef1-46d5-8349-ff9a87fb8758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@value='Approve'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@value='Approve'])[1]</value>
      <webElementGuid>0bec0909-715a-49a7-93a3-5b4506d0e508</webElementGuid>
   </webElementProperties>
</WebElementEntity>
