<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ok</name>
   <tag></tag>
   <elementGuidId>da93be3e-c94a-4a5a-b735-3b27c04c5bb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value='Ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value='Ok']</value>
      <webElementGuid>f1763a3b-8857-45ee-b0a4-b8adcbc7837e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
