<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SearchClinician</name>
   <tag></tag>
   <elementGuidId>45358449-afd4-4bf5-bf98-f31ae23e182f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'inputSearch')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'inputSearch')]</value>
      <webElementGuid>4efb981e-4703-4b25-8c2b-01484f84972f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
