<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Height</name>
   <tag></tag>
   <elementGuidId>a894c347-70b2-4a43-9235-08ebff9bd115</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'HEIGHT')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'HEIGHT')]</value>
      <webElementGuid>9bac7631-87ab-40e8-aa71-23c2c26a515a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
