<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SpecialistAddress</name>
   <tag></tag>
   <elementGuidId>3391b8d6-c8f7-49f3-a4ee-0025f10e92e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'SPECIALISTADDRESS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'SPECIALISTADDRESS')]</value>
      <webElementGuid>a06f1d43-31a9-4608-a8c3-5e659735a592</webElementGuid>
   </webElementProperties>
</WebElementEntity>
