<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DiagnosisDate</name>
   <tag></tag>
   <elementGuidId>0bafcebb-cdec-4a84-82e0-fc30103c3650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'DIAGNOSISDATE')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'DIAGNOSISDATE')]</value>
      <webElementGuid>1f0d9211-2863-4dc1-bd5e-3dfd126bea41</webElementGuid>
   </webElementProperties>
</WebElementEntity>
