<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_BasicInfo</name>
   <tag></tag>
   <elementGuidId>bce60f23-0dcb-4f83-b9c7-9fbd0e56728b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,&quot;MedicalForm&quot;)]/div[3]/div//span//div[1]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,&quot;MedicalForm&quot;)]/div[3]/div//span//div[1]//a</value>
      <webElementGuid>0098e2a0-9229-4e9a-bd1a-223936b0fee6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
