<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Stage</name>
   <tag></tag>
   <elementGuidId>856d0794-88f9-40fb-a3bf-fba59ea56b1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@id,'DIAGNOSIS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@id,'DIAGNOSIS')]</value>
      <webElementGuid>ea52712c-a976-4622-a7ee-d42aa17432f2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
