<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_CurrentMedication</name>
   <tag></tag>
   <elementGuidId>dd14d452-e27e-4caf-af96-d80e76f96931</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[contains(@id,'CURRENTMEDICATIONS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@id,'CURRENTMEDICATIONS')]</value>
      <webElementGuid>d3955520-dcf5-4f7e-a3dd-a510ebc3ccc9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
