<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Logout</name>
   <tag></tag>
   <elementGuidId>9e02a1b5-d981-4bba-935d-ec351293b189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>63e48919-7657-4af4-8b58-2db35261e32b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
