<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Previous</name>
   <tag></tag>
   <elementGuidId>25807cbc-d807-4542-872a-9eb5c010e838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='Previous']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='Previous']</value>
      <webElementGuid>ce268fe6-d970-476f-a446-670834ceedfd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
