<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Today</name>
   <tag></tag>
   <elementGuidId>2b9df774-5f91-46fc-8ed0-28cd4130273b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='Today']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='Today']</value>
      <webElementGuid>eeb11bd8-b907-4211-bac2-363650ae91f8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
