<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_Interest_NotAtAll</name>
   <tag></tag>
   <elementGuidId>ef5b9639-d0dc-4f40-9344-879a7287cc39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus0']//div[contains(@id,'RangeSliderObject')]/div[2]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus0']//div[contains(@id,'RangeSliderObject')]/div[2]/div[4]</value>
      <webElementGuid>6ee2a170-25f3-4563-ad77-93107daf0ea6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
