<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_ThoughtsNearly</name>
   <tag></tag>
   <elementGuidId>a5cd4b63-9ed8-4555-9a7d-9c881719b635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus8']//div[contains(@id,'RangeSliderObject')]/div[2]/div[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus8']//div[contains(@id,'RangeSliderObject')]/div[2]/div[10]</value>
      <webElementGuid>a61204bc-a85e-4f6e-9ec6-732781673e06</webElementGuid>
   </webElementProperties>
</WebElementEntity>
