<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_FeelingTiredSeveral</name>
   <tag></tag>
   <elementGuidId>54dc483f-c936-4a2c-a86c-9a87028ddade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus3']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus3']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      <webElementGuid>b4641812-dd41-4391-af30-f47e24401d8c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
