<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_TroubleFallingSeveral</name>
   <tag></tag>
   <elementGuidId>3485c221-4a3c-45a4-ba2c-bc275ed4388c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus2']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus2']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      <webElementGuid>0a6253f9-954d-40ab-afe2-ae31114c0e3a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
