<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_FeelingDown_Several</name>
   <tag></tag>
   <elementGuidId>f03b5e7a-a481-4b1c-aae4-45bff47f7b98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus1']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus1']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      <webElementGuid>b6962f7e-69fc-4a83-8c5c-b1b72ef6a328</webElementGuid>
   </webElementProperties>
</WebElementEntity>
