<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_ConcentrateNotAtAll</name>
   <tag></tag>
   <elementGuidId>f6bcd091-75c6-4c87-b26a-d2bc9129e7b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus6']//div[contains(@id,'RangeSliderObject')]/div[2]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus6']//div[contains(@id,'RangeSliderObject')]/div[2]/div[4]</value>
      <webElementGuid>3485102a-46d2-49b1-bc17-49796851a053</webElementGuid>
   </webElementProperties>
</WebElementEntity>
