<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_MovingNotAtAll</name>
   <tag></tag>
   <elementGuidId>87dd8dd6-1a5d-466d-a9d1-2ccc7c18db76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus7']//div[contains(@id,'RangeSliderObject')]/div[2]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus7']//div[contains(@id,'RangeSliderObject')]/div[2]/div[4]</value>
      <webElementGuid>ab59a6cd-02f5-463e-84aa-354d5695fa7d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
