<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_PoorAppetiteMorethan</name>
   <tag></tag>
   <elementGuidId>17c88a92-1b96-4ff9-8bb5-f0d941292e49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus4']//div[contains(@id,'RangeSliderObject')]/div[2]/div[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus4']//div[contains(@id,'RangeSliderObject')]/div[2]/div[8]</value>
      <webElementGuid>9b3ec306-e48f-40f2-add2-38e7921f8870</webElementGuid>
   </webElementProperties>
</WebElementEntity>
