<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range_FeelingBadSeveral</name>
   <tag></tag>
   <elementGuidId>09a24b89-d934-46c0-9b67-b4c03f24e5bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input_to_focus5']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input_to_focus5']//div[contains(@id,'RangeSliderObject')]/div[2]/div[6]</value>
      <webElementGuid>4db44514-9245-4ed8-83e7-a2602bbc8679</webElementGuid>
   </webElementProperties>
</WebElementEntity>
