<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ActivateConfirm</name>
   <tag></tag>
   <elementGuidId>294ae104-c84c-42bc-9c87-956976c91673</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='DBHealthWidgets_wtActivateUser_block_wtActions']//input[@value='Confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='DBHealthWidgets_wtActivateUser_block_wtActions']//input[@value='Confirm']</value>
      <webElementGuid>d01eb436-2285-4817-ad38-5f7ac1b69974</webElementGuid>
   </webElementProperties>
</WebElementEntity>
