<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Deactivate</name>
   <tag></tag>
   <elementGuidId>6753b757-5b22-49b3-b41d-c0c34c569615</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;DBHealthWidgets_wtDeactivateUser_block_wtContent&quot;]/div[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DBHealthWidgets_wtDeactivateUser_block_wtContent&quot;]/div[1]/span</value>
      <webElementGuid>f24c6120-e8ca-4b65-915e-27be649e93fd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
