<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_SearchResources</name>
   <tag></tag>
   <elementGuidId>cefcad1f-3e7d-47e8-b4fe-764b0020884b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'lstbxTags')]/parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'lstbxTags')]/parent::div</value>
      <webElementGuid>a17cf9fc-a9b5-498d-8501-467aac7b7e1e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
