<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SearchResources</name>
   <tag></tag>
   <elementGuidId>8428d13d-7531-4a72-baa6-eb540feb50b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@class='select2-search-field']//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@class='select2-search-field']//input</value>
      <webElementGuid>cf10b21b-3465-4a85-aff6-f7a8ef2fd702</webElementGuid>
   </webElementProperties>
</WebElementEntity>
