<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page_Title</name>
   <tag></tag>
   <elementGuidId>25cad9f5-2308-4db6-a0b4-a34af5390802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='heading1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class='heading1']</value>
      <webElementGuid>e067b76c-ac2e-4e1d-814c-e84f8c62c200</webElementGuid>
   </webElementProperties>
</WebElementEntity>
