<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_result2</name>
   <tag></tag>
   <elementGuidId>2e391df6-ae55-4707-918e-a457b81ef387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='select2-results']//li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='select2-results']//li[2]</value>
      <webElementGuid>bdef8752-02a1-4fe6-86e2-858612c45c7b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
