<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_result1</name>
   <tag></tag>
   <elementGuidId>6a94fba9-37e1-4b98-a272-9680f1fbd160</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='select2-results']//li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='select2-results']//li[1]</value>
      <webElementGuid>6fb08123-ee5a-4d68-8023-2d841377ed32</webElementGuid>
   </webElementProperties>
</WebElementEntity>
