<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Resources</name>
   <tag></tag>
   <elementGuidId>a7fbd808-ce1e-43f3-bfb7-2b4c34ebe6fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'SearchBar')]//select[contains(@id,'lstbxTags')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'SearchBar')]//select[contains(@id,'lstbxTags')]</value>
      <webElementGuid>a29a337d-e76b-473f-b6ef-bacd95d869d1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
