<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_UploadPhotos</name>
   <tag></tag>
   <elementGuidId>36265028-d5c7-4cc7-a387-82f386f366c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;DBHealthWidgets_wt11_block_OutSystemsUIWeb_wt20_block_wtContent_wtMainContent_wtChatBox2Block_Dropzone_wtWBDropzone_block_wtSuccessEvent&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DBHealthWidgets_wt11_block_OutSystemsUIWeb_wt20_block_wtContent_wtMainContent_wtChatBox2Block_Dropzone_wtWBDropzone_block_wtSuccessEvent&quot;]</value>
      <webElementGuid>ad734d40-1953-4553-b335-257dabd71573</webElementGuid>
   </webElementProperties>
</WebElementEntity>
