<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_UploadPhotos</name>
   <tag></tag>
   <elementGuidId>36265028-d5c7-4cc7-a387-82f386f366c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='DBHealthWidgets_wt11_block_OutSystemsUIWeb_wt20_block_wtContent_wtMainContent_wtChatBox2Block_wtButtonContainer']//div[@id='DBHealthWidgets_wt11_block_OutSystemsUIWeb_wt20_block_wtContent_wtMainContent_wtChatBox2Block_wtDropboxContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='DBHealthWidgets_wt11_block_OutSystemsUIWeb_wt20_block_wtContent_wtMainContent_wtChatBox2Block_wtButtonContainer']//div[@id='DBHealthWidgets_wt11_block_OutSystemsUIWeb_wt20_block_wtContent_wtMainContent_wtChatBox2Block_wtDropboxContainer']</value>
      <webElementGuid>ef0ed821-124e-4b0e-ad38-04a91f32fdbe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
