<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Notes</name>
   <tag></tag>
   <elementGuidId>017873a0-986d-431b-9e60-be5c02c7971c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'wtTitle')]//span[text()='Notes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'wtTitle')]//span[text()='Notes']</value>
      <webElementGuid>b662961b-c819-4a5d-9bb8-8a7ee92500b1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
