<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Upcoming</name>
   <tag></tag>
   <elementGuidId>e2d06283-c655-4139-8e71-1763dba36e04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'Tabs_Header')]//div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'Tabs_Header')]//div[2]</value>
      <webElementGuid>01163db4-f177-483e-816b-bee10be52ed0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
