<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Pending</name>
   <tag></tag>
   <elementGuidId>12ce9213-f7ef-419d-a5ba-fc187ce94e0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'Tabs_Header')]//div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'Tabs_Header')]//div[3]</value>
      <webElementGuid>0f51407e-8d07-4ebc-9c62-ddab6f679dee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
