<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Previous</name>
   <tag></tag>
   <elementGuidId>1d713d28-2d50-4cb7-a499-3ed4fda00230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'Tabs_Header')]//div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'Tabs_Header')]//div[4]</value>
      <webElementGuid>dd9c80d4-d0e7-4087-9609-412daf9c3bb1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
