<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_Record</name>
   <tag></tag>
   <elementGuidId>e9c120b4-8df3-4987-9579-4e65d7e3efa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'CompletedConsultationTable')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'CompletedConsultationTable')]</value>
      <webElementGuid>0849e55c-d3d3-474d-845d-fcc517e60ee9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
