<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DeactivateConfirm</name>
   <tag></tag>
   <elementGuidId>bbae069b-6933-4dca-8a9f-19ef2cec151d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='DBHealthWidgets_wtDeactivateUser_block_wtActions']//input[@value='Confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='DBHealthWidgets_wtDeactivateUser_block_wtActions']//input[@value='Confirm']</value>
      <webElementGuid>87b44eee-1955-4b00-b0b7-95172d3dc322</webElementGuid>
   </webElementProperties>
</WebElementEntity>
