<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Activate</name>
   <tag></tag>
   <elementGuidId>b918c2fd-061f-42e0-adf0-9d6821607311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;DBHealthWidgets_wtActivateUser_block_wtContent&quot;]/div[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DBHealthWidgets_wtActivateUser_block_wtContent&quot;]/div[1]/span</value>
      <webElementGuid>c8aeb992-5f1d-41a4-9d11-f6898970ea49</webElementGuid>
   </webElementProperties>
</WebElementEntity>
