<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Deactivate</name>
   <tag></tag>
   <elementGuidId>d7043c15-a005-439f-9c41-75d2891bd262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;DBHealthWidgets_wtDeactivateUser_block_wtContent&quot;]/div[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DBHealthWidgets_wtDeactivateUser_block_wtContent&quot;]/div[1]/span</value>
      <webElementGuid>31b5499f-04d5-4416-ab82-d156bcb7eb4e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
