<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue_invalid</name>
   <tag></tag>
   <elementGuidId>78e5df4d-7ecf-4fe0-8a3c-677b2030295c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'ErrorModal1_block_wtActions')]//input[@value='Continue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'ErrorModal1_block_wtActions')]//input[@value='Continue']</value>
      <webElementGuid>35aa20d6-ab59-4fb1-9fc5-9bef2a50edb8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
