<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal_success_message</name>
   <tag></tag>
   <elementGuidId>ee647ea8-e99e-41cf-9f10-903be70fecde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'wtSuccessModal_block_wtContent')]//span[@class='heading4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'wtSuccessModal_block_wtContent')]//span[@class='heading4']</value>
      <webElementGuid>d5425e64-da14-4abb-a2bf-6dc7330be240</webElementGuid>
   </webElementProperties>
</WebElementEntity>
