<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_ConfirmPassword</name>
   <tag></tag>
   <elementGuidId>9e41aecf-fab2-44f7-be42-7f4ef006168f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,'Input_ConfirmPassword')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,'Input_ConfirmPassword')]</value>
      <webElementGuid>2736bcbe-bfc8-4b92-939d-ba27929c124d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
