<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_NewPassword</name>
   <tag></tag>
   <elementGuidId>f1ed51ea-01c9-443e-9d39-0975a5ca0d38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,'Input_NewPassword')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,'Input_NewPassword')]</value>
      <webElementGuid>15152106-935b-4431-a3f6-c5b8df60a353</webElementGuid>
   </webElementProperties>
</WebElementEntity>
