<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Q3_4_Over</name>
   <tag></tag>
   <elementGuidId>6683c4b9-2b1f-4282-93da-d83d51f37875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'wtListCheckupQuestion_ctl04_wtctn_RangeSlider')]//div[contains(@id,'wtRangeSliderObject')]//div[text()='4-Over']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'wtListCheckupQuestion_ctl04_wtctn_RangeSlider')]//div[contains(@id,'wtRangeSliderObject')]//div[text()='4-Over']</value>
      <webElementGuid>b76dff4a-ecad-490a-ae9d-ef571fedc8fd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
