<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DeclineYes</name>
   <tag></tag>
   <elementGuidId>f32352d8-3d9e-4bdc-a957-888a86f67830</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'DeclineModal_block_wtActions')]//input[@value='Yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'DeclineModal_block_wtActions')]//input[@value='Yes']</value>
      <webElementGuid>adaa36cb-f923-4915-8af1-965206478811</webElementGuid>
   </webElementProperties>
</WebElementEntity>
