<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1_Decline</name>
   <tag></tag>
   <elementGuidId>184c68d2-4700-4354-b5ee-62c26b6bad06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'ConsultationsRequested')]//tbody//tr[1]//td[6]//input[@value='Decline']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'ConsultationsRequested')]//tbody//tr[1]//td[6]//input[@value='Decline']</value>
      <webElementGuid>d0d28a04-b4e6-45b8-a298-57354d14cf4a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
