<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Previous</name>
   <tag></tag>
   <elementGuidId>0dcc259d-de9b-42cf-aec2-dc01665e5e29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'Tabs_Header')]//div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'Tabs_Header')]//div[4]</value>
      <webElementGuid>542fc8ae-839e-452e-b561-988b6d792b89</webElementGuid>
   </webElementProperties>
</WebElementEntity>
