<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Notes</name>
   <tag></tag>
   <elementGuidId>2d8a39dd-7380-4c10-abb0-61c8e8f3a979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Notes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Notes']</value>
      <webElementGuid>cbfd7150-4f5f-4171-b5b9-5baea45b80be</webElementGuid>
   </webElementProperties>
</WebElementEntity>
