<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_PSA</name>
   <tag></tag>
   <elementGuidId>37d5dccf-34ee-4c28-8f45-e016a9400d62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='PSA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='PSA']</value>
      <webElementGuid>4ba96125-cd40-43f8-a922-3568ccd674c2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
