<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>718212aa-3abd-424e-bc55-dc34df2927f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='DBHealthWidgets_wtNewNoteModal2_block_wtActions']//input[@value='Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='DBHealthWidgets_wtNewNoteModal2_block_wtActions']//input[@value='Save']</value>
      <webElementGuid>9bba8d14-9145-48be-a015-683f9e1b9e87</webElementGuid>
   </webElementProperties>
</WebElementEntity>
