<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1_Date</name>
   <tag></tag>
   <elementGuidId>6ec63a81-06f0-426b-8f12-b51452f06c7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'PatientNotes2Table')]//tbody//tr[1]//td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'PatientNotes2Table')]//tbody//tr[1]//td[1]</value>
      <webElementGuid>cbe60d50-905e-4697-9d25-a969d237db4e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
