<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBRecord1</name>
   <tag></tag>
   <elementGuidId>dfb1426e-0e17-4864-a0e2-80c8a59cc702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@id,'PatientNotes2Table')]//tbody//tr[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@id,'PatientNotes2Table')]//tbody//tr[1]</value>
      <webElementGuid>de8a6e8d-ce0c-4ba7-a36d-cf18bf1bedc7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
