<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Partner</name>
   <tag></tag>
   <elementGuidId>838d9142-eafd-4631-9e41-4d948ea6dcc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,&quot;ListOfNeedProblemFamily&quot;)]//div[1]//div//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,&quot;ListOfNeedProblemFamily&quot;)]//div[1]//div//input</value>
      <webElementGuid>52292678-ae2b-4aae-80eb-bfb4aa9d1f82</webElementGuid>
   </webElementProperties>
</WebElementEntity>
