<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Urinary</name>
   <tag></tag>
   <elementGuidId>67b939cf-7295-4b8c-9e09-a73fae7d971c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,&quot;ListOfNeedProblemPhysical&quot;)]//div[4]//div//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,&quot;ListOfNeedProblemPhysical&quot;)]//div[4]//div//input</value>
      <webElementGuid>4e93526d-68f2-4fe8-b398-cb0f3486a615</webElementGuid>
   </webElementProperties>
</WebElementEntity>
