<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Work</name>
   <tag></tag>
   <elementGuidId>d4e778a2-f0f2-49b4-a864-e283cde5ce30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,&quot;ListOfNeedProblemPractical&quot;)]//div[1]//div//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,&quot;ListOfNeedProblemPractical&quot;)]//div[1]//div//input</value>
      <webElementGuid>a6e6a42a-3955-48c7-a46a-2f72070300b6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
