<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Sadness</name>
   <tag></tag>
   <elementGuidId>5e71b03e-db52-421b-a5df-d38bb18b8179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,&quot;tListOfNeedProblemEmotional&quot;)]//div[3]//div//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,&quot;tListOfNeedProblemEmotional&quot;)]//div[3]//div//input</value>
      <webElementGuid>2a71e060-8378-4026-ad4b-ebbcaa0c789e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
