<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range6_distress</name>
   <tag></tag>
   <elementGuidId>d7756b2f-0e3c-492f-8b66-a22701ed5e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'RangeSliderObject')]/div[2]/div[16]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'RangeSliderObject')]/div[2]/div[16]</value>
      <webElementGuid>40a301ff-1dcd-4280-9c3f-97a584819560</webElementGuid>
   </webElementProperties>
</WebElementEntity>
