<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Others</name>
   <tag></tag>
   <elementGuidId>5d419270-7c58-4615-8b7c-1322ff4bb0f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[contains(@id,&quot;OTHERPROBLEMS&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@id,&quot;OTHERPROBLEMS&quot;)]</value>
      <webElementGuid>90475e31-7c92-46c5-af27-828fb5a32f3a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
