<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CreateClinician</name>
   <tag></tag>
   <elementGuidId>d5def019-205c-4952-8dae-7619a3d03985</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value='Create']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value='Create']</value>
      <webElementGuid>90e6cc05-94ce-43f6-85e1-5e40d1d4e320</webElementGuid>
   </webElementProperties>
</WebElementEntity>
