<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ClinicianFirstName</name>
   <tag></tag>
   <elementGuidId>c50272d6-eedf-4383-88c1-8c843a21a673</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'Clinician_FirstName')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'Clinician_FirstName')]</value>
      <webElementGuid>d3f533e9-52ac-4a6b-b25a-13e59c23df4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
