<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ClinicianPhoneNumber</name>
   <tag></tag>
   <elementGuidId>8b224d39-6391-4da0-8d57-add6656fae27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'Clinician_PhoneNumber')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'Clinician_PhoneNumber')]</value>
      <webElementGuid>91c57ce8-27fb-4df5-b50d-0e728df68415</webElementGuid>
   </webElementProperties>
</WebElementEntity>
