<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_ClinicianEmail</name>
   <tag></tag>
   <elementGuidId>c8c32a92-7072-419e-9970-0088177442ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'Clinician_Email')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'Clinician_Email')]</value>
      <webElementGuid>22e9c736-f0a9-45f8-b31b-8454d7d83fe3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
