<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal_LogoutConfirmation</name>
   <tag></tag>
   <elementGuidId>e1def9b8-7077-410b-a7e7-1dcdf51712c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='MainPopup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='MainPopup']</value>
      <webElementGuid>f339040f-0eae-4507-858f-536c3bc74f35</webElementGuid>
   </webElementProperties>
</WebElementEntity>
