<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Journal</name>
   <tag></tag>
   <elementGuidId>527e5cf3-2ed5-4c3f-bfa9-033bcf29c9c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,&quot;LifeEventTypeRecord&quot;)]//span//div[3]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,&quot;LifeEventTypeRecord&quot;)]//span//div[3]//input</value>
      <webElementGuid>3e03f637-ba69-47cd-a399-9a958f2facf8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
