<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Treatment</name>
   <tag></tag>
   <elementGuidId>baba8631-e3ea-4da6-8dce-0cf002535a7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,&quot;LifeEventTypeRecord&quot;)]//span//div[6]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,&quot;LifeEventTypeRecord&quot;)]//span//div[6]//input</value>
      <webElementGuid>9ffa52e3-3bd3-421c-a5bb-82334e93e27a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
